# Changes here will be overwritten by Copier
_commit: v0.2.0
_src_path: gh:alan-turing-institute/python-project-template
coc: our_coc
email: lfrance@turing.ac.uk
full_name: Lydia France
license: MIT
min_python_version: '3.10'
org: LydiaFrance
project_name: birdlabelling
project_short_description: Trying out wing marker labelling
python_name: birdlabelling
typing: no_typing
url: https://github.com/LydiaFrance/birdlabelling
